name: human_anatomy
description: An updated version of the Flutter package human_anatomy that now suppors null-safety.
version: 1.0.0
author: TRO JEAN CEDRIC(seniorjean)<tro.oppong@gmail.com>
credit: SK SHAMIMUL ISLAM (SHEIKHSOFT)<sheikhsoft.com@gmail.com>
homepage: https://github.com/Sheikhsoft/human_anatomy

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/head.svg
    - assets/left_ear.svg
    - assets/right_ear.svg
    - assets/left_eye.svg
    - assets/right_eye.svg
    - assets/nose.svg
    - assets/mouth.svg
    - assets/neck.svg
    - assets/chest.svg
    - assets/abdomin.svg
    - assets/pelvis.svg
    - assets/publs.svg
    - assets/left_soulder.svg
    - assets/right_soulder.svg
    - assets/left_arm.svg
    - assets/right_arm.svg
    - assets/left_elbow.svg
    - assets/right_elbow.svg
    - assets/left_forearm.svg
    - assets/right_forearm.svg
    - assets/left_wrist.svg
    - assets/right_wrist.svg
    - assets/left_hand.svg
    - assets/right_hand.svg
    - assets/left_thigh.svg
    - assets/right_thigh.svg
    - assets/left_knee.svg
    - assets/right_knee.svg
    - assets/left_leg.svg
    - assets/right_leg.svg
    - assets/left_ankle.svg
    - assets/right_ankle.svg
    - assets/left_foot.svg
    - assets/right_foot.svg